### ISSUE TITLE
Support for kubectl plugin?

### ISSUE THREAD

**Issue by mvladev** [gardener/gardenctl#12]
As of k8s 1.8 `kubectl` supports [plugins](https://kubernetes.io/docs/tasks/extend-kubectl/kubectl-plugins/). 

As an end-user I would like to do: 

```bash
$ kubectl --context=some-context --namespace=some-ns garden show prometheus
# or simply
$ kubectl garden show prometheus
# with gardencli using the current context I use and namespace.
```

This will allow for a quick debugging without the need to switch context, namespaces and etc every single time.

**Comment by DockToFuture** [comment]
Gardenctl is settled one layer above of kubectl and therefore its not perfectly suitable to provide it as plugin for kubectl. It covers more than just the pure functionality of interacting with one cluster. 
As an end user you can still set your context for a kubeconfig file and the little overhead seems to be worth the abstraction.  
`$ g k config set-context alice -- --cluster=shoot-garden-core-i028584  --user=alice --namespace=alice-ns`
But we can let it open for discussion, if more user feels your way the more native one, then we can think about providing it as a plugin. But for now, we stick with it as a separate tool.

**Comment by vlerenc** [comment]
@DockToFuture Following up above: Is there some support in plugins to tweak (for the duration of the session/shell/environment) the active Kubernetes cluster? Then the integration as plugin could be even slicker than via a dedicated CLI.

Alternatively, we could re-discuss the idea we had a long time ago: manipulate the kubeconfig, add new clusters (whenever we target it) and switch the current context. However, the disadvantages were significant:
* it alters the targetted Kubernetes cluster and the Gardener plugin would have to "remember" the garden cluster, so that targets can be dropped, etc.
* it would have to alter the kubeconfig file itself, which may not be editable or would make repos dirty if it's no user local file, but e.g. (like in our case with the git-checked-in Kubify clusters) actual git repos (problem that Andreas F. and I noticed in the beginning)

**Comment by DockToFuture** [comment]
A kubectl plugin is nothing more than plugin.yaml file and an executable. I could store the config in `~/.kube/plugins/gardenctl/config` instead of `~/.garden/config` together with the executable and plugin.yaml file, which looks like this.

```yaml
name: "gardenctl"                 # REQUIRED: the plugin command name, to be invoked under 'kubectl'
shortDesc: "Gardenctl plugin"    # REQUIRED: the command short description, for help
command: "./gardenctl"             # REQUIRED: the command, binary, or script to invoke when running the plugin
```
But currently the call would be `kubectl plugin gardenctl kubectl get pods`, which feels wrong. Better would be something like this`kubectl plugin gardenctl get pods`. If we use the plugin approach, we should redesign the commands. 
And when I got your point, you want to use the set namespace and context for kubectl for the plugin cmd as well, either via a kubectl parameter or the current-context, right?

**Comment by ialidzhikov** [comment]
I am interested in this one. Will try to poc something in my free time.

**Comment by DockToFuture** [comment]
Sounds good, if we could also get also rid of ```--``` to signify the end of the options for the cmds, it would be a decent plugin with ease to use.

**Comment by DockToFuture** [comment]
I will look at the second part.

**Comment by neo-liang-sap** [comment]
@ialidzhikov , we went through historical comments of this issue and saw your last comment at  https://github.com/gardener/gardenctl/issues/12#issuecomment-503439134, is there any update on this or is this requirement still valid? 
meanwhile i will open another issue to track whether it's possible to remove `--` from command line
Thanks
-Neo

**Comment by ialidzhikov** [comment]
Some time ago I wanted to try out the kubectl approach as I see that gardenctl-like tools are all kubectl plugins. In general kubectl extensibility evolved much after gardenctl was out. I hope that with the kubectl plugin approach there will be a possibility to get some functionality for free - for example the cluster access, I assume that the framework has already functionality to check for the `KUBECONFIG` env var, `--kubeconfig` passed flag or default location and in this way allow the plugin command author to access this data in easy and unified way.
In general I see it also as  an opportunity to remove the current code duplications (there is a lot 😕  ), refactor the existing code to make it testable and add unit test coverage (10% unit test coverage for similar project is not enough).

Unfortunately I have no capacity now for something similar.

/unassign

**Comment by vlerenc** [comment]
It is not 100% clear what we will gain by a `kubectl` plugin (what is stated in the description with the arguments seems not to be possible), but it would definitely speak to the community and it features an extension concept, which we also need (e.g. to package IaaS specific commands separately).

Since we anyhow need to overhaul it and make it safer and more extensible, this discussion here shall be merged into the larger epic https://github.com/gardener/gardenctl/issues/499 that is about `gardenctl` v2.

/duplicate #499
/close
