### ISSUE TITLE
Cannot use the openstack cli

### ISSUE THREAD

**Issue by ialidzhikov** [gardener/gardenctl#170]
**Describe the bug**
Cannot use the openstack cli with gardenctl.

**To Reproduce**
```
$ g openstack server list
Missing value auth-url required for auth plugin password

$ openstack --version
openstack 4.0.0
```

**Gardenctl Version (please complete the following information):**
```
$ g version
gardenctl:
		version     : v0.16.0
		build date  : 2019-12-26
		go version  : go1.13.4
		go compiler : gc
		platform    : darwin/amd64
```

**Additional context**

**Comment by neo-liang-sap** [comment]
i tried to look into this issue but didn't figure out the root cause, i'm sharing what i found if a bit helpful:
- the error `Missing value auth-url...` is due to missing authentication url when running `g openstack` command.
- the authURL is injected in line https://github.com/gardener/gardenctl/blob/master/pkg/cmd/operate.go#L215 `cloudProfileConfig `
- `cloudProfileConfig ` is getting values from function `getOpenstackCloudProfileConfig` https://github.com/gardener/gardenctl/blob/10a537942b94234914758c0f6d053dc1cf218ecd/pkg/cmd/operate.go#L287
- the final error comes from while trying to decode the raw data from `in.Spec.ProviderConfig.Raw` https://github.com/gardener/gardenctl/blob/10a537942b94234914758c0f6d053dc1cf218ecd/pkg/cmd/operate.go#L312

i confirmed the `in.Spec.ProviderConfig.Raw` contains authURL - as it's confidential i can't share the data content, so i assume the error occurs in `Decode` function which comes from `Decode` function in `apimachinery` package.

I'm not familiar with `apimachinery` package so above are as far as i can go...hope this help a bit

**Comment by neo-liang-sap** [comment]
Hi @ialidzhikov / @DockToFuture :
Based on my comments above i'm trying to go further.
I decoded the `in.Spec.ProviderConfig.Raw` just using plain go function and getting the json contents.
- i used demo code like this (at end of function `getOpenstackCloudProfileConfig `):
```
	case in.Spec.ProviderConfig.Raw != nil:
		if _, _, err := decoder.Decode(in.Spec.ProviderConfig.Raw, nil, out); err != nil {
			return nil, fmt.Errorf("cannot decode providerConfig of core.gardener.cloud/v1beta1.CloudProfile %s", in.Name)
		}
		var rawS map[string]interface{}
		if err := json.Unmarshal(in.Spec.ProviderConfig.Raw, &rawS); err != nil {
			panic(err)
		}
		rawS["count"] = 1
		out, _ := json.Marshal(rawS)
		println(string(out))
```

- and the json structure is looking like below:

![image](https://user-images.githubusercontent.com/42594392/77663087-a2d83c80-6fb7-11ea-9c17-388d5d2e930c.png)

So as you can see there are an array of `keystoneURLs ` in json content but no `KeyStoneURL`

So my questions are:

- in latest version of https://github.com/gardener/gardener-extension-provider-openstack/blob/master/pkg/apis/openstack/v1alpha1/types_cloudprofile.go , both `keystoneURLs ` and `KeyStoneURL` exist, current `gardenctl` depends on `gardener-extension@v1.1.0` which only have  `KeyStoneURL`, so this issue is an version mis-match between `gardenctl` and `/gardener-extension-provider-openstack`?

- in api response of data structure `in.Spec.ProviderConfig.Raw` there's no field `KeyStoneURL`, is this an bug for g/g ?

Not sure i'm heading correct way , if you have time it would be much appreciated if you can review my investigation here...

Thanks!
