### ISSUE TITLE
Create a GitHub Action for automatic build & push of Docker Image to DockerHub

### ISSUE THREAD

**Issue by Magoli1** [gardener/gardenctl#210]
Hey everyone,

I really like that you are providing a Dockerfile for easy consumption of gardenctl! 👍 
What do you think about a GitHub Action that automatically builds the corresponding docker image and pushes it to DockerHub, whenever there are changes? This would allow an easier consumption, without the need of building it first. Also the integration into CI/CD scenarios would be seamless.

I would be very happy to provide a PR for this. Nevertheless, it requires credentials in the secret section of GitHub from your side, to be able to push the image to DockerHub.

Let me know your thoughts on this 👍 

Cheers
Robert

**Comment by petersutter** [comment]
That would be nice 👍 , however I would suggest to adapt the pipeline definition in order to build and publish the image.
Examples can be found [here](https://github.com/gardener/dashboard/blob/master/.ci/pipeline_definitions#L10-L17) or [here](https://github.com/gardener/ops-toolbelt/blob/master/.ci/pipeline_definitions#L10-L25)

The documentation can be found [here](https://gardener.github.io/cc-utils/traits/publish.html)

This way (instead of github actions) it would be nicely integrated into our builds and published on every release of the component, plus you do not need to specify the container registry credentials. WDYT?

**Comment by Magoli1** [comment]
Hey @petersutter any updates on this?

BR Robert

**Comment by petersutter** [comment]
Hi @Magoli1, sorry I'm not a code owner of gardenctl but the PR looks good
PTAL @gardener/gardenctl-maintainers

**Comment by petersutter** [comment]
maybe @AndreasBurger can also have a quick look at #215 if he spots anything that needs to be changed
