### ISSUE TITLE
As non garden admin I am not able to get logs or ssh into a node

### ISSUE THREAD

**Issue by wiegandf** [gardener/gardenctl#253]
**Describe the bug**
I am not an admin in this garden but wanted to use gardenctl to manage the shoots in my project. With the fix in https://github.com/gardener/gardenctl/pull/249 I am able to target my shoot, but I can't do anything with it like ssh into a node or retrieving logs. 

**To Reproduce**
1. Which target was set 'gardenctl get target'
```
- kind: shoot
  name: cds-b-sus
```
2. Which command was entered [e.g. 'gardenctl show vpn-seed']
`gardentctl logs vpn-shoot` and `gardentctl ssh ip-a-b-c-d.ec2.internal`

3. What was the output of the command 

```
logs
shoots.core.gardener.cloud is forbidden: User "system:serviceaccount:garden-x:x-sa" cannot list resource "shoots" in API group "core.gardener.cloud" at the cluster scope

ssh
secrets "seed-aws-us1" is forbidden: User "system:serviceaccount:garden-x:x-sa" cannot get resource "secrets" in API group "" in the namespace "garden"
```
**Expected behavior**
SSH into shoot nodes or retrieving logs of vpn-shoot works.

**Gardenctl Version (please complete the following information):**
```
gardenctl:
		version     : v0.20.0
		build date  : 2020-08-10
		go version  : go1.14.6
		go compiler : gc
		platform    : darwin/amd64
```

**Comment by tedteng** [comment]
Hi @petersutter, regarding `gardenctl ssh`,   I did some experiments ，as non-admin user can't get machine information due to lack of permission access seed. Do you have any idea is there any ways we can fetch the machine info?  Thanks

// fetch seed kubeonfig and list machines 
https://github.com/gardener/gardenctl/blob/b7303bd65d5ac37c64c791e25f4fa4bf52eeaf90/pkg/cmd/ssh.go#L150-L160

// fetch seed kubeonfig
https://github.com/gardener/gardenctl/blob/b7303bd65d5ac37c64c791e25f4fa4bf52eeaf90/pkg/cmd/target.go#L683-L695

**Comment by petersutter** [comment]
I'm not aware of any other way (without having access to the seed)
cc @prashanth26

**Comment by tedteng** [comment]
> I'm not aware of any other way (without having access to the seed)
> cc @prashanth26

Thanks. @petersutter and @prashanth26 let me know if there anywhere which I can reference the information. 

so far the solution I working on is getting node from shoot kubeconfig, and use aws cli as well, to fetch necessary information from the cloud directly etc, instance id, security group id etc.

**Comment by tedteng** [comment]
@petersutter @wiegandf welcome any feedback as PR https://github.com/gardener/gardenctl/pull/263

**Comment by tedteng** [comment]
@wiegandf for `logs` it seems not able to access it due to that required seed permission as most of key pods (kube-api etc.) schedule in master node (Seed). You can't check pod log from Seed now. but you will have `ssh` feature at this point which allows you access your node to check system log eg kubelet log  if you need

**Comment by petersutter** [comment]
> @petersutter @wiegandf welcome any feedback as PR #263

@tedteng just wanted to let you know that I'm currently reviewing the PR. Will continue with the review on friday (after my vacation tomorrow)
