### ISSUE TITLE
Cannot get shell to node if cluster is waking up

### ISSUE THREAD

**Issue by danielfoehrKn** [gardener/gardenctl#260]
**Describe the bug**

Cannot get shell to a node if the Shoot  is waking up. 

**To Reproduce**
1. Which target was set 'gardenctl get target'
2. Which command was entered [e.g. 'gardenctl show vpn-seed']
3. What was the output of the command 

1. Wake up a Shoot (not 100 % reconciled yet)
- Shoot.Spec.hibernation.enabled=false 
- Shoot.Status.hibernated = true

2. Try to use `gardenctl shell <node>`  

```
g shell shoot--dev--aws-glinux2-worker-z1-5d6cd56cb6-d9rk5
Error: shoot "aws-glinux2" is hibernated
```

**Expected behavior**

It should be possible to get a shell to a cluster that is currently waking up.
This is e.g useful when troubleshooting a cluster that is unable to wake up due to node joining problems.

**Screenshots**

**Gardenctl Version (please complete the following information):**
 - latest

**Additional context**

**Comment by tedteng** [comment]
/assign 
will have a look

**Comment by danielfoehrKn** [comment]
Thanks!

**Comment by tedteng** [comment]
sorry for later reply due to working on that issue today, The `gardenctl shell` will create pod then schedule to a certain node. that's mean it will highly depend on the Kubernetes cluster. If a node can't join the cluster, the pod will not schedule to that issue node to check kubelet log.  we have to use traditional way `gardenctl ssh` which use cloud client, eg `aws cli` interaction with cloud then check node logs through bastion host as jump server.

**Comment by danielfoehrKn** [comment]
I think there are two use cases
 - waking up fails (but worker nodes already joined) 
 - there are multiple worker pools with in my case different OS.
   One pool was unable to join but I wanted to get a shell to the health pool due to testing purposes. I see though that this is an edge case that I only needed due to testing. 

Overall I think this is more of an edge case so I am open to close it for now.

**Comment by danielfoehrKn** [comment]
Closing this as there are more important issues to work on.
If we see more demands in this direction we can open it again.

/close
