### ISSUE TITLE
Add `gardenctl show infra` command

### ISSUE THREAD

**Issue by dansible** [gardener/gardenctl#477]
It would be great to have a command to show all the cloud provider infra created by gardener (VPCs, Subnets, Routes, VMs, etc).

Some of this functionality is implemented in the `gardenctl infra orphan list` command (see https://github.com/gardener/gardenctl/issues/475 and https://github.com/gardener/gardenctl/issues/252) but would need to be extracted/refactored to be able to use in this case as well

**Comment by vlerenc** [comment]
Related, @rfranzke recently proposed to pull out all resources from the Terraform file. We already pull some out to hand them over to other components (such as the VPC ID), but not yet all.

@dansible @neo-liang-sap @DockToFuture What would be your way to get to this data, if this proposal gets picked up? I ask, because it would be a waste to duplicate the work and `gardenctl` couldn't reliably "follow" Gardener unless it gets released together with it, but also then it shouldn't duplicate the knowledge and details of the infrastructure extensions.

**Comment by jfortin-sap** [comment]
@vlerenc @rfranzke  We would basically use the cloud provider cli to retrieve all the resources and print it out in a presentable digestible format? Would this be fine?
