### ISSUE TITLE
Connecting to a AWS instance that exists but failed to join the cluster via `gardenctl ssh` always fails

### ISSUE THREAD

**Issue by stoyanr** [gardener/gardenctl#480]
**Describe the bug**
Connecting to a AWS instance that exists but failed to join the cluster via `gardenctl ssh` always fails.

**To Reproduce**
```
$ gardenctl target seed canary
...
$ gardenctl target shoot d029266smp-haas
...
$ gardenctl ssh ip-10-250-0-27.eu-central-1.compute.internal

Warning:
Be aware that you are entering an untrusted environment!
Do not enter credentials or sensitive data within the ssh session that cluster owners should not have access to.

Downloaded id_rsa key
Check Public IP

(1/4) Fetching data from target shoot cluster
Data fetched from target shoot cluster.

(2/4) Setting up bastion host security group
Bastion host security group set up.

(3/4) Creating bastion host and node host security group
Bastion host instance i-0a1ebaf36c14f2234 Initializing.

Bastion host instance running.
Opened SSH Port on Node.
waiting for 10 seconds to retry
waiting for 10 seconds to retry
IP 18.196.163.225 port 22 is reachable
SSH gardener@18.196.163.225 => gardener@ip-10-250-0-27.eu-central-1.compute.internal
Warning: Permanently added '18.196.163.225' (ECDSA) to the list of known hosts.
channel 0: open failed: connect failed: Connection refused
stdio forwarding failed
kex_exchange_identification: Connection closed by remote host
exit status 255
(4/4) Cleanup
Cleaning up bastion host configurations...

Starting cleanup

  (1/3) Cleaning up bastion host instance
TERMINATINGINSTANCES	i-0a1ebaf36c14f2234
CURRENTSTATE	32	shutting-down
PREVIOUSSTATE	16	running
  (2/3) Close SSH Port on Node.
  Closed SSH Port on Node.
True
  (3/3) Clean up bastion host security group


Bastion host configurations successfully cleaned up.
```

Note that since the instance doesn't join the cluster, it's deleted every 20 min. I tried with 2 of these instances with the same result.

**Expected behavior**
It should successfully connect to the instance via ssh

**Gardenctl Version (please complete the following information):**
```
$ g version
gardenctl:
		version     : v0.24.0
		build date  : 2020-12-02
		go version  : go1.14.12
		go compiler : gc
		platform    : darwin/amd64
```

**Additional context**

**Comment by stoyanr** [comment]
@ialidzhikov You mentioned that you had to workaround this as well, could you please share your experience?

**Comment by neo-liang-sap** [comment]
Hi @stoyanr ,

Thanks for reporting this.

When i looked at this shoot i didn't see the node you mentioned (should have gone) , i tried ssh to another normal node and ssh seems ok.

I also met same problem when ssh to some machine (not only for aws).

From the log you pasted:
- the ip and port is reachable (`IP 18.196.163.225 port 22 is reachable`)
- `Warning: Permanently added '18.196.163.225' (ECDSA) to the list of known hosts.` ->ssh connection is initially built and local machine get remote machine fingerprint
- and then the connection is failed (`Connection closed by remote host`)

I believe this issue is more related to remote machine, maybe the machine ssh server function is not working properly or network issue, just like sometimes you use `ssh` to a machine you get same error.

Do you have a better idea how to improve this from gardenctl side? 

Thanks!
-Neo
![image](https://user-images.githubusercontent.com/42594392/100892086-e8f58080-34f4-11eb-963f-34aff310b447.png)
![image](https://user-images.githubusercontent.com/42594392/100891325-1beb4480-34f4-11eb-9b25-169c9c263a0c.png)

**Comment by stoyanr** [comment]
@neo-liang-sap Yes, I guess you are right. I tried to connect to the machine via a bastion created with `gardenctl` after adding a manual long sleep in the `gardenctl` code as advised by @ialidzhikov. Unfortunately this still didn't work. Connecting to the bastion works, however, from there to the actual instance I got "connecton refused" even though the instance was there and running according to AWS CLI:
```
ip-10-250-96-31:/home/gardener # ssh -i ./id_rsa gardener@10.250.0.4
ssh: connect to host 10.250.0.4 port 22: Connection refused
```
And now with both shoots where it was reproducible gone, I can't even reproduce it anymore. Closing this issue.
